### ISSUE TITLE
Can't get this to work with askForLocation

### ISSUE THREAD

**Issue by mofman** [idk-tn/yii2-botman#1]
I can't get this to work with askForLocation am I doing something wrong? All my other questions respond properly, using this code I never get the response?

`

        $this->askForLocation('Please share your location:', function ($location) {
            $this->say('Received: '.print_r($location, true));
        }, null, [
            'message' => [
                'quick_replies' => json_encode([
                    [
                        'content_type' => 'location'
                    ]
                ])
            ]
        ]);

`

**Comment by machour** [comment]
Hey @mofman, what error are you getting?

**Comment by mofman** [comment]
Hey @machour no errors but the callback isnt run, all the other asks work fine but askForLocation doesnt respond.

**Comment by machour** [comment]
Reported in https://github.com/botman/botman/issues/639, closing this as irrelevant to yii2-botman

**Comment by mofman** [comment]
I reported this in both repos but as expected the maintainer of botman suspects the issue lies with the caching https://github.com/botman/botman/issues/699 . Not sure how to debug this.

**Comment by machour** [comment]
Your report mention https://github.com/DaveFerger/botman-yii2-cache, not idk-tn/yii2-botman..

**Comment by mofman** [comment]
Actually I have tried both, they both work great except when listening for Location.

**Comment by machour** [comment]
Couldn't guess that ^^
Is your code available online?

If not, start by tracing calls in this module cache file, like this for example in all members:

```diff
+++ b/Cache.php
@@ -48,6 +48,7 @@ class Cache extends Component implements CacheInterface
         */
        public function pull($key, $default = null)
        {
+               file_put_contents('/tmp/cache.log', 'pull(' . $key . ')', FILE_APPEND);
                $value = $this->get($key, $default);
                $this->cache->delete($key);
```

see what is called and when (please, do switch back to idk/yii2-botman so we're on the same codebase while debugging this)

**Comment by mofman** [comment]
I've just created gist of my code - https://gist.github.com/mofman/c064c73a532ddf5e065d3952d363a428 

I've just added the logging, it doesnt appear to call 'GET' when I send the location using the quick action button, however when I type something and hit send it adds to the log and then responds with the same question again. 

Thanks for your assistance

**Comment by machour** [comment]
Could you add askImage() for example that would call $this->askForImages()?
The idea is to have a working askForImage and use it to compare what happens inside botman.
(I looked at the code, it doesn't seems to be handling things differently)

Also, can you check your server Apache logs and extract all the calls performed by Facebook?

**Comment by mofman** [comment]
Actually I cant get askForImages to work either, its as if Botman is currently only listening for plain text answers, is there something I should be doing to listen for these special answers?

I'll fetch the logs now too.

**Comment by machour** [comment]
From what I've (quickly) seen in botman source code, there's nothing special about it, and if it works for image, it should work for location..

**Comment by mofman** [comment]
Yea I can't get either images or location to work right now, only plain text answers work.

**Comment by machour** [comment]
@mofman sorry didn't get the time to work on this. Did you find the problem?

**Comment by mofman** [comment]
Its no problem @machour, thank you for your help, it turns out you need to load the Facebook Image & Locations drivers manually aswell

        DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookImageDriver::class);
        DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookLocationDriver::class);

Sorry for troubling you, and thanks for your assistance

**Comment by machour** [comment]
Nice to know, thank you so much for the feedback

**Comment by sugoireed** [comment]
Had a similar problem. The solution is that you need to also import/load/add the location driver for the driver you are using i.e Facebook Location driver

DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookLocationDriver::class);
